-- Optional demo seed data for SallPlan.
-- Run after schema.sql if you want starter rooms and schedules in Supabase.

insert into teachers (id, name, username, role, teacher_type, active) values
  ('admin', 'Admin', 'admin', 'admin', 'admin', true),
  ('t1', 'Frau Mueller', 'mueller', 'teacher', 'class_teacher', true),
  ('t2', 'Herr Weber', 'weber', 'teacher', 'class_teacher', true),
  ('t3', 'Frau Eischen', 'eischen', 'teacher', 'class_teacher', true),
  ('t4', 'Herr Klein', 'klein', 'teacher', 'subject_teacher', true),
  ('t5', 'Frau Schneider', 'schneider', 'teacher', 'class_teacher', true),
  ('t6', 'Frau Becker', 'becker', 'teacher', 'subject_teacher', true)
on conflict (id) do nothing;

insert into rooms (id, name, type, building, floor, capacity, responsible_teacher_id, active) values
  ('r1', 'Saal C2.1', 'fixed_schedule', 'Hauptgebaeude', '1. Etage', 24, 't3', true),
  ('r2', 'Saal C2.2', 'fixed_schedule', 'Hauptgebaeude', '1. Etage', 22, 't1', true),
  ('r3', 'Saal C3.1', 'fixed_schedule', 'Hauptgebaeude', '2. Etage', 25, 't2', true),
  ('r4', 'Saal C4.1', 'fixed_schedule', 'Hauptgebaeude', '3. Etage', 24, 't5', true),
  ('r5', 'Foerderraum', 'free_booking', 'Hauptgebaeude', 'Erdgeschoss', 8, null, true),
  ('r6', 'Musikraum', 'free_booking', 'Nebengebaeude', 'Erdgeschoss', 20, null, true),
  ('r7', 'Informatikraum', 'free_booking', 'Hauptgebaeude', '2. Etage', 18, null, true),
  ('r8', 'Besprechungsraum', 'free_booking', 'Verwaltung', '1. Etage', 10, null, true),
  ('r9', 'Bibliothek', 'free_booking', 'Hauptgebaeude', 'Erdgeschoss', 26, null, true),
  ('r10', 'Mehrzweckraum', 'free_booking', 'Nebengebaeude', 'Erdgeschoss', 60, null, true)
on conflict (id) do nothing;

insert into recurring_releases (id, room_id, day, slot_id, reason, created_by, valid_from, valid_until) values
  ('rr1', 'r1', 'Freitag', 'row1', 'Schwimmen', 't3', '2025-09-15', '2026-07-15'),
  ('rr2', 'r1', 'Freitag', 'row2', 'Schwimmen', 't3', '2025-09-15', '2026-07-15'),
  ('rr3', 'r2', 'Dienstag', 'row3', 'Turnen', 't1', '2025-09-15', '2026-07-15'),
  ('rr4', 'r3', 'Donnerstag', 'row4', 'Musik in anderem Raum', 't2', '2025-09-15', '2026-07-15')
on conflict (id) do nothing;

insert into school_holidays (id, name, start_date, end_date, created_by) values
  ('h1', 'Sommerferien', '2026-07-16', '2026-09-13', 'admin'),
  ('h2', 'Herbstferien', '2026-10-26', '2026-10-30', 'admin')
on conflict (id) do nothing;

insert into fixed_schedule (room_id, day, slot_id, subject, teacher_id, status) values
  ('r1', 'Montag', 'row1', 'Deutsch', 't3', 'fix_belegt'),
  ('r1', 'Montag', 'row2', 'Rechnen', 't1', 'fix_belegt'),
  ('r1', 'Montag', 'row3', 'Rechnen', 't2', 'fix_belegt'),
  ('r1', 'Montag', 'row4', 'Deutsch', 't4', 'fix_belegt'),
  ('r1', 'Montag', 'row5', 'Sciences', 't5', 'fix_belegt'),
  ('r1', 'Montag', 'row6', 'Sciences', 't6', 'fix_belegt'),
  ('r1', 'Dienstag', 'row1', 'Deutsch', 't3', 'fix_belegt'),
  ('r1', 'Dienstag', 'row2', 'Deutsch', 't1', 'fix_belegt'),
  ('r1', 'Dienstag', 'row3', 'Rechnen', 't2', 'fix_belegt'),
  ('r1', 'Dienstag', 'row4', 'Luxemburgisch', 't4', 'fix_belegt'),
  ('r1', 'Dienstag', 'row5', 'Musik', 't5', 'fix_belegt'),
  ('r1', 'Mittwoch', 'row1', 'Deutsch Fr', 't3', 'fix_belegt'),
  ('r1', 'Mittwoch', 'row2', 'Rechnen', 't1', 'fix_belegt'),
  ('r1', 'Mittwoch', 'row3', 'Deutsch', 't2', 'fix_belegt'),
  ('r1', 'Mittwoch', 'row4', 'Deutsch', 't4', 'fix_belegt'),
  ('r1', 'Mittwoch', 'row5', 'Vieso', 't5', 'fix_belegt'),
  ('r1', 'Mittwoch', 'row6', 'Vieso', 't6', 'fix_belegt'),
  ('r1', 'Donnerstag', 'row1', 'Sport', 't3', 'fix_belegt'),
  ('r1', 'Donnerstag', 'row2', 'Rechnen', 't1', 'fix_belegt'),
  ('r1', 'Donnerstag', 'row3', 'Rechnen', 't2', 'fix_belegt'),
  ('r1', 'Donnerstag', 'row4', 'Deutsch', 't4', 'fix_belegt'),
  ('r1', 'Donnerstag', 'row5', 'Sciences', 't5', 'fix_belegt'),
  ('r1', 'Freitag', 'row1', 'Schwimmen', 't3', 'fix_belegt'),
  ('r1', 'Freitag', 'row2', 'Schwimmen', 't1', 'fix_belegt'),
  ('r1', 'Freitag', 'row3', 'Deutsch', 't2', 'fix_belegt'),
  ('r1', 'Freitag', 'row4', 'Deutsch', 't4', 'fix_belegt'),
  ('r1', 'Freitag', 'row5', 'Basteln', 't5', 'fix_belegt'),
  ('r1', 'Freitag', 'row6', 'Basteln', 't6', 'fix_belegt'),
  ('r2', 'Montag', 'row1', 'Deutsch', 't1', 'fix_belegt'),
  ('r2', 'Montag', 'row2', 'Rechnen', 't2', 'fix_belegt'),
  ('r2', 'Montag', 'row3', 'Rechnen', 't4', 'fix_belegt'),
  ('r2', 'Montag', 'row4', 'Deutsch', 't5', 'fix_belegt'),
  ('r2', 'Montag', 'row5', 'Sciences', 't6', 'fix_belegt'),
  ('r2', 'Montag', 'row6', 'Sciences', 't3', 'fix_belegt'),
  ('r2', 'Dienstag', 'row1', 'Deutsch', 't1', 'fix_belegt'),
  ('r2', 'Dienstag', 'row2', 'Deutsch', 't2', 'fix_belegt'),
  ('r2', 'Dienstag', 'row3', 'Rechnen', 't4', 'fix_belegt'),
  ('r2', 'Dienstag', 'row4', 'Luxemburgisch', 't5', 'fix_belegt'),
  ('r2', 'Dienstag', 'row5', 'Musik', 't6', 'fix_belegt'),
  ('r2', 'Mittwoch', 'row1', 'Deutsch Fr', 't1', 'fix_belegt'),
  ('r2', 'Mittwoch', 'row2', 'Rechnen', 't2', 'fix_belegt'),
  ('r2', 'Mittwoch', 'row3', 'Deutsch', 't4', 'fix_belegt'),
  ('r2', 'Mittwoch', 'row4', 'Deutsch', 't5', 'fix_belegt'),
  ('r2', 'Mittwoch', 'row5', 'Vieso', 't6', 'fix_belegt'),
  ('r2', 'Mittwoch', 'row6', 'Vieso', 't3', 'fix_belegt'),
  ('r2', 'Donnerstag', 'row1', 'Sport', 't1', 'fix_belegt'),
  ('r2', 'Donnerstag', 'row2', 'Rechnen', 't2', 'fix_belegt'),
  ('r2', 'Donnerstag', 'row3', 'Rechnen', 't4', 'fix_belegt'),
  ('r2', 'Donnerstag', 'row4', 'Deutsch', 't5', 'fix_belegt'),
  ('r2', 'Donnerstag', 'row5', 'Sciences', 't6', 'fix_belegt'),
  ('r2', 'Freitag', 'row1', 'Schwimmen', 't1', 'fix_belegt'),
  ('r2', 'Freitag', 'row2', 'Schwimmen', 't2', 'fix_belegt'),
  ('r2', 'Freitag', 'row3', 'Deutsch', 't4', 'fix_belegt'),
  ('r2', 'Freitag', 'row4', 'Deutsch', 't5', 'fix_belegt'),
  ('r2', 'Freitag', 'row5', 'Basteln', 't6', 'fix_belegt'),
  ('r2', 'Freitag', 'row6', 'Basteln', 't3', 'fix_belegt'),
  ('r3', 'Montag', 'row1', 'Deutsch', 't2', 'fix_belegt'),
  ('r3', 'Montag', 'row2', 'Rechnen', 't4', 'fix_belegt'),
  ('r3', 'Montag', 'row3', 'Rechnen', 't5', 'fix_belegt'),
  ('r3', 'Montag', 'row4', 'Deutsch', 't6', 'fix_belegt'),
  ('r3', 'Montag', 'row5', 'Sciences', 't3', 'fix_belegt'),
  ('r3', 'Montag', 'row6', 'Sciences', 't1', 'fix_belegt'),
  ('r3', 'Dienstag', 'row1', 'Deutsch', 't2', 'fix_belegt'),
  ('r3', 'Dienstag', 'row2', 'Deutsch', 't4', 'fix_belegt'),
  ('r3', 'Dienstag', 'row3', 'Rechnen', 't5', 'fix_belegt'),
  ('r3', 'Dienstag', 'row4', 'Luxemburgisch', 't6', 'fix_belegt'),
  ('r3', 'Dienstag', 'row5', 'Musik', 't3', 'fix_belegt'),
  ('r3', 'Mittwoch', 'row1', 'Deutsch Fr', 't2', 'fix_belegt'),
  ('r3', 'Mittwoch', 'row2', 'Rechnen', 't4', 'fix_belegt'),
  ('r3', 'Mittwoch', 'row3', 'Deutsch', 't5', 'fix_belegt'),
  ('r3', 'Mittwoch', 'row4', 'Deutsch', 't6', 'fix_belegt'),
  ('r3', 'Mittwoch', 'row5', 'Vieso', 't3', 'fix_belegt'),
  ('r3', 'Mittwoch', 'row6', 'Vieso', 't1', 'fix_belegt'),
  ('r3', 'Donnerstag', 'row1', 'Sport', 't2', 'fix_belegt'),
  ('r3', 'Donnerstag', 'row2', 'Rechnen', 't4', 'fix_belegt'),
  ('r3', 'Donnerstag', 'row3', 'Rechnen', 't5', 'fix_belegt'),
  ('r3', 'Donnerstag', 'row4', 'Deutsch', 't6', 'fix_belegt'),
  ('r3', 'Donnerstag', 'row5', 'Sciences', 't3', 'fix_belegt'),
  ('r3', 'Freitag', 'row1', 'Schwimmen', 't2', 'fix_belegt'),
  ('r3', 'Freitag', 'row2', 'Schwimmen', 't4', 'fix_belegt'),
  ('r3', 'Freitag', 'row3', 'Deutsch', 't5', 'fix_belegt'),
  ('r3', 'Freitag', 'row4', 'Deutsch', 't6', 'fix_belegt'),
  ('r3', 'Freitag', 'row5', 'Basteln', 't3', 'fix_belegt'),
  ('r3', 'Freitag', 'row6', 'Basteln', 't1', 'fix_belegt'),
  ('r4', 'Montag', 'row1', 'Deutsch', 't4', 'fix_belegt'),
  ('r4', 'Montag', 'row2', 'Rechnen', 't5', 'fix_belegt'),
  ('r4', 'Montag', 'row3', 'Rechnen', 't6', 'fix_belegt'),
  ('r4', 'Montag', 'row4', 'Deutsch', 't3', 'fix_belegt'),
  ('r4', 'Montag', 'row5', 'Sciences', 't1', 'fix_belegt'),
  ('r4', 'Montag', 'row6', 'Sciences', 't2', 'fix_belegt'),
  ('r4', 'Dienstag', 'row1', 'Deutsch', 't4', 'fix_belegt'),
  ('r4', 'Dienstag', 'row2', 'Deutsch', 't5', 'fix_belegt'),
  ('r4', 'Dienstag', 'row3', 'Rechnen', 't6', 'fix_belegt'),
  ('r4', 'Dienstag', 'row4', 'Luxemburgisch', 't3', 'fix_belegt'),
  ('r4', 'Dienstag', 'row5', 'Musik', 't1', 'fix_belegt'),
  ('r4', 'Mittwoch', 'row1', 'Deutsch Fr', 't4', 'fix_belegt'),
  ('r4', 'Mittwoch', 'row2', 'Rechnen', 't5', 'fix_belegt'),
  ('r4', 'Mittwoch', 'row3', 'Deutsch', 't6', 'fix_belegt'),
  ('r4', 'Mittwoch', 'row4', 'Deutsch', 't3', 'fix_belegt'),
  ('r4', 'Mittwoch', 'row5', 'Vieso', 't1', 'fix_belegt'),
  ('r4', 'Mittwoch', 'row6', 'Vieso', 't2', 'fix_belegt'),
  ('r4', 'Donnerstag', 'row1', 'Sport', 't4', 'fix_belegt'),
  ('r4', 'Donnerstag', 'row2', 'Rechnen', 't5', 'fix_belegt'),
  ('r4', 'Donnerstag', 'row3', 'Rechnen', 't6', 'fix_belegt'),
  ('r4', 'Donnerstag', 'row4', 'Deutsch', 't3', 'fix_belegt'),
  ('r4', 'Donnerstag', 'row5', 'Sciences', 't1', 'fix_belegt'),
  ('r4', 'Freitag', 'row1', 'Schwimmen', 't4', 'fix_belegt'),
  ('r4', 'Freitag', 'row2', 'Schwimmen', 't5', 'fix_belegt'),
  ('r4', 'Freitag', 'row3', 'Deutsch', 't6', 'fix_belegt'),
  ('r4', 'Freitag', 'row4', 'Deutsch', 't3', 'fix_belegt'),
  ('r4', 'Freitag', 'row5', 'Basteln', 't1', 'fix_belegt'),
  ('r4', 'Freitag', 'row6', 'Basteln', 't2', 'fix_belegt')
on conflict (room_id, day, slot_id) do nothing;
